Android UI
ANSSI-FR/ultrablue pull request #24
Opened 2023-01-29 18:17 UTC by lfalkau

Implements the encryption to match the server again, and improves the UI of the Android client.

2023-02-01 13:31 UTC, lfalkau commented
The current PR makes the Android client work with the server on `dev`, without the nonce tweak.

2023-03-20 10:11 UTC, RaitoBezarius commented
Is there anything that can be done to get this PR merged? I am trying to package Ultrablue in NixOS at the moment and it seems like our only choice is to either package this PR to generate the Android app or to use the fosdem-2023 tag in the meantime.

2023-03-20 13:15 UTC, nbouchinet-anssi commented
> Is there anything that can be done to get this PR merged? I am trying to package Ultrablue in NixOS at the moment and it seems like our only choice is to either package this PR to generate the Android app or to use the fosdem-2023 tag in the meantime.

Hi @RaitoBezarius, thanks for trying to package it in NixOS, we can definitely do something to help, we could create a first stable tag but will have to review a bit more the android client code before merging it.

I'm not quite sure to understand why you need to generate the Android app in order to package it though. Could you explain a bit more ?

2023-03-20 13:20 UTC, RaitoBezarius commented
> > Is there anything that can be done to get this PR merged? I am trying to package Ultrablue in NixOS at the moment and it seems like our only choice is to either package this PR to generate the Android app or to use the fosdem-2023 tag in the meantime.
> 
> Hi @RaitoBezarius, thanks for trying to package it in NixOS, we can definitely do something to help, we could create a first stable tag but will have to review a bit more the android client code before merging it.

FWIW: https://github.com/NixOS/nixpkgs/pull/222068 is our integration in initrd and https://github.com/NixOS/nixpkgs/pull/222062 is the binary (a stable tag would be awesome).

> I'm not quite sure to understand why you need to generate the Android app in order to package it though. Could you explain a bit more ?

I don't know exactly your plans, but currently, from what I am seeing:

FOSDEM-2023 Android app is incompatible with master.

This PR seems to solve the issue. 

If in the future, it is possible to have protocol incompatibilities, in nixpkgs, we can package the server with the Android app such that a user can do something like `nix-build -A ultrablue-server.android-app` and get his own APK compatible to this very specific `ultrablue-server` whatever revision or version it might be.

It also take care of something which would probably be interested in Ultrablue scope: proper reproducibility and source provenance tracking of the Android application for such a "critical" piece of software.

Of course, it's possible with F-Droid and all that stuff, it is just not too hard to do in nixpkgs. :)

---

Anyway, I am not going to merge the PR too soon, but it would be awesome if Ultrablue made it in the upcoming release of NixOS (23.05), at end of May, meaning, I probably have ~one month if I want to make this part of the next stable release.

2023-03-20 13:21 UTC, RaitoBezarius commented
Also, for completeness, I am working on SecureBoot in NixOS and a bit of TPM2, and we would like to make this part of the next stable release, so having also Ultrablue would make the first release with somewhat of a SecureBoot support -- very interesting for our users. :)

2023-03-20 13:55 UTC, nbouchinet-anssi commented
> FOSDEM-2023 Android app is incompatible with master.
Oh thats true, will try to merge soon, sorry for that.

2023-03-20 14:06 UTC, RaitoBezarius commented
> > FOSDEM-2023 Android app is incompatible with master.
> 
> Oh thats true, will try to merge soon, sorry for that.

No worries :). I am excited to use this in a more official/production capacity. Thank YOU for doing that work and open-sourcing it ;).

2023-05-05 15:19 UTC, RaitoBezarius commented
@nbouchinet-anssi Hey there, did you have any time on this? Nixpkgs will be shipping a stable release with the FOSDEM tag at the moment, I believe.

2023-07-04 10:28 UTC, RaitoBezarius commented
Hi there, I see you had successful presentations in Pass the Salt, any news on this PR?

2023-07-12 08:02 UTC, nbouchinet-anssi commented
Hello @RaitoBezarius, I'm starting a code review now. Sorry for the delay.

2023-07-12 11:46 UTC, RaitoBezarius commented
> Hello @RaitoBezarius, I'm starting a code review now. Sorry for the delay.

Great news, don't hesitate to ping when you will have a release, in the meantime, I have suspended all integration of Ultrablue in NixOS.

2023-07-12 16:06 UTC, nbouchinet-anssi requested changes
Review is not over yet, will continue next week.

2023-07-12 16:06 UTC, nbouchinet-anssi commented on clients/Android/ultrablue/app/src/main/java/fr/gouv/ssi/ultrablue/fragments/DeviceFragment.kt
> +                        context?.let {
If I understood well the commit message, this only stops the application to crash, the user will not be able to edit the device name.

I'll open an issue and link it to this commit, this has to be fixed before any merge.

2023-07-12 16:06 UTC, nbouchinet-anssi commented on clients/Android/ultrablue/app/src/main/java/fr/gouv/ssi/ultrablue/database/Device.kt
> +    val uid: UUID, // UUID used to enroll the phone device to the server
So this UUID represents the phone ?

2023-07-12 16:06 UTC, nbouchinet-anssi commented on clients/Android/ultrablue/app/src/main/java/fr/gouv/ssi/ultrablue/model/QRValidate.kt
> +}
As said in the comments, those functions checks for valid format, not for working validity, the isKeyValid does not assert that the key is indeed a valid AES-GCM key matching the laptop one.

2023-07-12 16:06 UTC, nbouchinet-anssi commented on clients/Android/ultrablue/app/src/main/java/fr/gouv/ssi/ultrablue/model/UltrablueProtocol.kt
> +const val RESPONSE = 16
Can't we declare it with an enum style using the `iota` keyword ?

2023-07-12 16:06 UTC, nbouchinet-anssi commented on clients/Android/ultrablue/app/src/main/java/fr/gouv/ssi/ultrablue/model/CryptoManager.kt
> +    }
We should either use two symmetric AES-GCM keys, one for each message direction or use a direction bit in order to avoid encrypted message replay.

2023-07-13 17:33 UTC, Tecol87 commented
What is the latest revision where the server and client are compatible?

2023-07-21 12:25 UTC, nbouchinet-anssi commented
Since the project is in a WIP state, we have not yet clearly defined its scope nor its roadmap, we will work on this clarification after the summer holidays, until that day, no stable tags for clients and server will be released and you should not use the project in production.

However, @Tecol87 if you want to test the project, you should be able to use the [fosdem branch](https://github.com/ANSSI-FR/ultrablue/tree/fosdem-2023).

Anyway, thank's for your interest for the project and sorry for this issue.

2023-07-22 14:28 UTC, Tecol87 commented
@nbouchinet-anssi 
Thank you very much for the clarification and your work on this project!
Then I will setup my new production system with tpm2-totp and cryptographic-id.
On my testsystem I will test this project until it is production ready.

2023-10-28 19:38 UTC, RaitoBezarius commented
Hi there @nbouchinet-anssi , hope you had great summer holidays. It would be helpful on my side to understand if the project has still interest from ANSSI for further development or was it deprioritized or something.

We are moving on with TPM2 in NixOS and it would be a nice showcase to offer Ultrablue to our users.

2025-03-17 10:37 UTC, closed without merging