Minor tweaks to Android client
ANSSI-FR/ultrablue pull request #3
Opened 2022-07-20 15:04 UTC by kerneis-anssi

2022-07-21 08:29 UTC, lfb-anssi requested changes

2022-07-21 08:29 UTC, lfb-anssi commented on clients/Android/README.md
> +General tips Android Studio tips, not specific to Ultrablue:
Did you meant "General Android studio tips"?

2022-07-22 08:56 UTC, kerneis-anssi commented
Please take another look.

2022-07-25 06:04 UTC, kerneis-anssi commented
@lfb-anssi can you please confirm this is okay to merge for you?

2022-07-25 07:38 UTC, lfb-anssi approved these changes
Looks good to me!

2022-07-25 07:43 UTC, merged